### ISSUE TITLE
DLL not found

### ISSUE THREAD

**Issue by abitrolly** [UserLiubov/Baumer-Camera-in-Python#1]
Ошибка DLL из-за того, что полученный модуль в 45kB динамически слинкован с либами Baumer SDK, которые Python не может увидеть при импорте. Натравив [depends.exe](http://www.dependencywalker.com/) на .pyd файл можно увидеть, какие именно .dll требуются и положить их в соответствующее место. Где оно - ХЗ. С Linux проще всё это.

**Comment by abitrolly** [comment]
Если задача шире, чем просто разобраться со связкой C++ + Python, то лучше взять https://pypi.org/project/harvesters/ - стандартизированный интерфейс для работы с камерами, который данные сразу в `numpy` отдаёт.

**Comment by lbv-h** [comment]
Спасибо за помощь, harvesters помогла решить задачу. :)

вс, 15 сент. 2019 г. в 08:47, Anatoli Babenia <notifications@github.com>:
